// File: api/{resource}.ts
// Generated by: {agent-name}
// Date: {timestamp}
// Template: .trae/templates/typescript/api.template.ts

import { client } from './client';
import type { ApiResponse, PaginatedResponse } from './types';

export interface {Resource} {
  id: string;
  name: string;
  description?: string;
  status: 'active' | 'inactive';
  created_at: string;
  updated_at: string;
}

export interface Create{Resource}Request {
  name: string;
  description?: string;
}

export interface Update{Resource}Request {
  name?: string;
  description?: string;
  status?: 'active' | 'inactive';
}

export interface {Resource}ListParams {
  page?: number;
  page_size?: number;
  search?: string;
  status?: 'active' | 'inactive';
}

export interface {Resource}ListResponse {
  items: {Resource}[];
  pagination: {
    page: number;
    page_size: number;
    total: number;
    total_pages: number;
  };
}

export const {resource}Api = {
  list: async (params?: {Resource}ListParams): Promise<PaginatedResponse<{Resource}ListResponse>> => {
    const { data } = await client.get<PaginatedResponse<{Resource}ListResponse>>(
      '/api/v1/{resources}',
      { params }
    );
    return data;
  },

  get: async (id: string): Promise<ApiResponse<{Resource}>> => {
    const { data } = await client.get<ApiResponse<{Resource}>>(
      `/api/v1/{resources}/${id}`
    );
    return data;
  },

  create: async (payload: Create{Resource}Request): Promise<ApiResponse<{Resource}>> => {
    const { data } = await client.post<ApiResponse<{Resource}>>(
      '/api/v1/{resources}',
      payload
    );
    return data;
  },

  update: async (id: string, payload: Update{Resource}Request): Promise<ApiResponse<{Resource}>> => {
    const { data } = await client.put<ApiResponse<{Resource}>>(
      `/api/v1/{resources}/${id}`,
      payload
    );
    return data;
  },

  delete: async (id: string): Promise<ApiResponse<null>> => {
    const { data } = await client.delete<ApiResponse<null>>(
      `/api/v1/{resources}/${id}`
    );
    return data;
  },
};

export default {resource}Api;
