// File: {ComponentName}.tsx
// Generated by: {agent-name}
// Date: {timestamp}
// Template: .trae/templates/typescript/component.template.tsx

import React, { useState, useCallback, useMemo } from 'react';
import { Card } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Badge } from '@/components/ui/badge';
import { Skeleton } from '@/components/ui/skeleton';
import { useToast } from '@/components/ui/use-toast';

interface {ComponentName}Props {
  /** 标题 */
  title?: string;
  /** 数据列表 */
  items: {ItemType}[];
  /** 加载状态 */
  loading?: boolean;
  /** 点击回调 */
  onItemClick?: (item: {ItemType}) => void;
  /** 创建回调 */
  onCreate?: () => void;
  /** 删除回调 */
  onDelete?: (id: string) => void;
  /** 额外类名 */
  className?: string;
}

export const {ComponentName}: React.FC<{ComponentName}Props> = ({
  title = '默认标题',
  items,
  loading = false,
  onItemClick,
  onCreate,
  onDelete,
  className = ''
}) => {
  const { toast } = useToast();
  const [searchTerm, setSearchTerm] = useState('');
  const [selectedId, setSelectedId] = useState<string | null>(null);

  const filteredItems = useMemo(() => {
    if (!searchTerm) return items;
    const lowerSearch = searchTerm.toLowerCase();
    return items.filter(item =>
      item.name.toLowerCase().includes(lowerSearch) ||
      (item.description && item.description.toLowerCase().includes(lowerSearch))
    );
  }, [items, searchTerm]);

  const handleItemClick = useCallback((item: {ItemType}) => {
    setSelectedId(item.id);
    onItemClick?.(item);
  }, [onItemClick]);

  const handleDelete = useCallback((e: React.MouseEvent, id: string) => {
    e.stopPropagation();
    onDelete?.(id);
    toast({
      title: '删除成功',
      description: '项目已删除',
    });
  }, [onDelete, toast]);

  const handleCreate = useCallback(() => {
    onCreate?.();
  }, [onCreate]);

  if (loading) {
    return (
      <Card className={`p-6 ${className}`}>
        <div className="space-y-4">
          <Skeleton className="h-8 w-1/4" />
          <div className="space-y-2">
            {[1, 2, 3].map(i => (
              <Skeleton key={i} className="h-16 w-full" />
            ))}
          </div>
        </div>
      </Card>
    );
  }

  return (
    <Card className={`p-6 ${className}`}>
      <div className="space-y-4">
        {/* Header */}
        <div className="flex items-center justify-between">
          <h2 className="text-xl font-semibold">{title}</h2>
          <div className="flex items-center gap-2">
            <Input
              type="search"
              placeholder="搜索..."
              value={searchTerm}
              onChange={(e) => setSearchTerm(e.target.value)}
              className="w-64"
            />
            {onCreate && (
              <Button onClick={handleCreate}>
                创建
              </Button>
            )}
          </div>
        </div>

        {/* List */}
        {filteredItems.length === 0 ? (
          <div className="text-center py-8 text-gray-500">
            {searchTerm ? '没有找到匹配的结果' : '暂无数据'}
          </div>
        ) : (
          <div className="space-y-2">
            {filteredItems.map((item) => (
              <div
                key={item.id}
                className={`
                  p-4 border rounded-lg cursor-pointer transition-all
                  hover:bg-gray-50 hover:shadow-sm
                  ${selectedId === item.id ? 'border-blue-500 bg-blue-50' : 'border-gray-200'}
                `}
                onClick={() => handleItemClick(item)}
              >
                <div className="flex items-start justify-between">
                  <div className="flex-1">
                    <div className="flex items-center gap-2">
                      <h3 className="font-medium">{item.name}</h3>
                      <Badge variant={item.status === 'active' ? 'default' : 'secondary'}>
                        {item.status === 'active' ? '启用' : '禁用'}
                      </Badge>
                    </div>
                    {item.description && (
                      <p className="text-sm text-gray-500 mt-1">{item.description}</p>
                    )}
                    <div className="text-xs text-gray-400 mt-2">
                      创建于 {new Date(item.created_at).toLocaleDateString()}
                    </div>
                  </div>
                  {onDelete && (
                    <Button
                      variant="ghost"
                      size="sm"
                      onClick={(e) => handleDelete(e, item.id)}
                      className="text-red-600 hover:text-red-700 hover:bg-red-50"
                    >
                      删除
                    </Button>
                  )}
                </div>
              </div>
            ))}
          </div>
        )}

        {/* Pagination */}
        {filteredItems.length > 0 && (
          <div className="flex items-center justify-between pt-4 border-t">
            <div className="text-sm text-gray-500">
              显示 {filteredItems.length} 项，共 {items.length} 项
            </div>
            <div className="flex items-center gap-2">
              <Button variant="outline" size="sm" disabled>
                上一页
              </Button>
              <Button variant="outline" size="sm" disabled>
                下一页
              </Button>
            </div>
          </div>
        )}
      </div>
    </Card>
  );
};

export default {ComponentName};
