// File: hooks/use{Feature}.ts
// Generated by: {agent-name}
// Date: {timestamp}
// Template: .trae/templates/typescript/hook.template.ts

import { useState, useCallback, useEffect } from 'react';
import type { {Resource} } from '@/api/{resource}';
import { {resource}Api } from '@/api/{resource}';

interface Use{Feature}Options {
  /** 初始页码 */
  initialPage?: number;
  /** 初始每页数量 */
  initialPageSize?: number;
  /** 是否自动加载 */
  autoLoad?: boolean;
}

interface Use{Feature}Return {
  /** 数据列表 */
  items: {Resource}[];
  /** 加载状态 */
  loading: boolean;
  /** 分页信息 */
  pagination: {
    page: number;
    pageSize: number;
    total: number;
    totalPages: number;
  };
  /** 搜索词 */
  search: string;
  /** 错误信息 */
  error: string | null;
  /** 加载数据 */
  load: () => Promise<void>;
  /** 分页切换 */
  setPage: (page: number) => void;
  /** 每页数量变更 */
  setPageSize: (size: number) => void;
  /** 搜索词变更 */
  setSearch: (search: string) => void;
  /** 创建 */
  create: (data: Partial<{Resource}>) => Promise<{Resource} | null>;
  /** 更新 */
  update: (id: string, data: Partial<{Resource}>) => Promise<{Resource} | null>;
  /** 删除 */
  remove: (id: string) => Promise<boolean>;
  /** 刷新 */
  refresh: () => Promise<void>;
}

export function use{Feature}(options: Use{Feature}Options = {}): Use{Feature}Return {
  const {
    initialPage = 1,
    initialPageSize = 20,
    autoLoad = true,
  } = options;

  const [items, setItems] = useState<{Resource}[]>([]);
  const [loading, setLoading] = useState(false);
  const [page, setPageState] = useState(initialPage);
  const [pageSize, setPageSizeState] = useState(initialPageSize);
  const [total, setTotal] = useState(0);
  const [search, setSearchState] = useState('');
  const [error, setError] = useState<string | null>(null);

  const load = useCallback(async () => {
    setLoading(true);
    setError(null);

    try {
      const response = await {resource}Api.list({
        page,
        page_size: pageSize,
        search: search || undefined,
      });

      if (response.code === 200) {
        setItems(response.data.items);
        setTotal(response.data.pagination.total);
      } else {
        setError(response.message);
      }
    } catch (err) {
      setError(err instanceof Error ? err.message : '加载失败');
    } finally {
      setLoading(false);
    }
  }, [page, pageSize, search]);

  const create = useCallback(async (data: Partial<{Resource}>): Promise<{Resource} | null> => {
    setLoading(true);
    setError(null);

    try {
      const response = await {resource}Api.create(data as any);
      if (response.code === 201 || response.code === 200) {
        await load();
        return response.data;
      } else {
        setError(response.message);
        return null;
      }
    } catch (err) {
      setError(err instanceof Error ? err.message : '创建失败');
      return null;
    } finally {
      setLoading(false);
    }
  }, [load]);

  const update = useCallback(async (id: string, data: Partial<{Resource}>): Promise<{Resource} | null> => {
    setLoading(true);
    setError(null);

    try {
      const response = await {resource}Api.update(id, data as any);
      if (response.code === 200) {
        await load();
        return response.data;
      } else {
        setError(response.message);
        return null;
      }
    } catch (err) {
      setError(err instanceof Error ? err.message : '更新失败');
      return null;
    } finally {
      setLoading(false);
    }
  }, [load]);

  const remove = useCallback(async (id: string): Promise<boolean> => {
    setLoading(true);
    setError(null);

    try {
      const response = await {resource}Api.delete(id);
      if (response.code === 200) {
        await load();
        return true;
      } else {
        setError(response.message);
        return false;
      }
    } catch (err) {
      setError(err instanceof Error ? err.message : '删除失败');
      return false;
    } finally {
      setLoading(false);
    }
  }, [load]);

  const setPage = useCallback((newPage: number) => {
    setPageState(newPage);
  }, []);

  const setPageSize = useCallback((newSize: number) => {
    setPageSizeState(newSize);
    setPageState(1);
  }, []);

  const setSearch = useCallback((newSearch: string) => {
    setSearchState(newSearch);
    setPageState(1);
  }, []);

  const refresh = useCallback(async () => {
    await load();
  }, [load]);

  useEffect(() => {
    if (autoLoad) {
      load();
    }
  }, [autoLoad, load]);

  return {
    items,
    loading,
    pagination: {
      page,
      pageSize,
      total,
      totalPages: Math.ceil(total / pageSize),
    },
    search,
    error,
    load,
    setPage,
    setPageSize,
    setSearch,
    create,
    update,
    remove,
    refresh,
  };
}

export default use{Feature};
