# File: app/api/{module}_router.py
# Generated by: {agent-name}
# Date: {timestamp}
# Template: .trae/templates/python/router.template.py

from fastapi import APIRouter, Depends, HTTPException, Query, UploadFile, File, Body
from typing import List, Optional
from pydantic import BaseModel, Field
from datetime import datetime
from app.core.dependencies import get_current_user
from app.services.{module}_service import {Model}Service
from app.schemas.{module}_schema import (
    {Model}Request,
    {Model}Response,
    {Model}ListResponse,
    {Model}UpdateRequest,
)

router = APIRouter(prefix="/api/v1/{module}", tags=["{Module}"])
service = {Model}Service()


class {Model}Request(BaseModel):
    """创建{module}请求模型"""
    name: str = Field(..., min_length=1, max_length=255, description="{module}名称")
    description: Optional[str] = Field(None, max_length=1000, description="描述")
    config: Optional[dict] = Field(default_factory=dict, description="配置")


class {Model}UpdateRequest(BaseModel):
    """更新{module}请求模型"""
    name: Optional[str] = Field(None, min_length=1, max_length=255)
    description: Optional[str] = Field(None, max_length=1000)
    status: Optional[str] = Field(None, pattern="^(active|inactive)$")
    config: Optional[dict] = None


class {Model}Response(BaseModel):
    """{module}响应模型"""
    id: str
    name: str
    description: Optional[str] = None
    status: str
    config: Optional[dict] = None
    created_at: datetime
    updated_at: datetime

    class Config:
        from_attributes = True


class PaginationMeta(BaseModel):
    """分页元数据"""
    page: int
    page_size: int
    total: int
    total_pages: int


class {Model}ListResponse(BaseModel):
    """{module}列表响应模型"""
    items: List[{Model}Response]
    pagination: PaginationMeta


@router.get("/", response_model={Model}ListResponse, summary="获取{module}列表")
async def list_{module}(
    page: int = Query(1, ge=1, description="页码"),
    page_size: int = Query(20, ge=1, le=100, description="每页数量"),
    search: Optional[str] = Query(None, max_length=255, description="搜索关键词"),
    status: Optional[str] = Query(None, pattern="^(active|inactive)$", description="状态筛选"),
    current_user = Depends(get_current_user),
):
    """
    获取{module}列表

    支持分页、搜索和状态筛选
    """
    skip = (page - 1) * page_size
    items, total = await service.list(
        skip=skip,
        limit=page_size,
        search=search,
        status=status,
        user_id=current_user.id,
    )

    total_pages = (total + page_size - 1) // page_size

    return {Model}ListResponse(
        items=[{Model}Response.model_validate(item) for item in items],
        pagination=PaginationMeta(
            page=page,
            page_size=page_size,
            total=total,
            total_pages=total_pages,
        ),
    )


@router.get("/{module}_id", response_model={Model}Response, summary="获取{module}详情")
async def get_{module}(
    {module}_id: str,
    current_user = Depends(get_current_user),
):
    """根据ID获取{module}详情"""
    item = await service.get({module}_id, user_id=current_user.id)
    if not item:
        raise HTTPException(status_code=404, detail="{Module} not found")
    return {Model}Response.model_validate(item)


@router.post("/", response_model={Model}Response, status_code=201, summary="创建{module}")
async def create_{module}(
    request: {Model}Request,
    current_user = Depends(get_current_user),
):
    """创建新的{module}"""
    item = await service.create(
        name=request.name,
        description=request.description,
        config=request.config,
        user_id=current_user.id,
    )
    return {Model}Response.model_validate(item)


@router.put("/{module}_id", response_model={Model}Response, summary="更新{module}")
async def update_{module}(
    {module}_id: str,
    request: {Model}UpdateRequest,
    current_user = Depends(get_current_user),
):
    """更新已存在的{module}"""
    item = await service.update(
        id={module}_id,
        user_id=current_user.id,
        name=request.name,
        description=request.description,
        status=request.status,
        config=request.config,
    )
    if not item:
        raise HTTPException(status_code=404, detail="{Module} not found")
    return {Model}Response.model_validate(item)


@router.delete("/{module}_id", status_code=204, summary="删除{module}")
async def delete_{module}(
    {module}_id: str,
    current_user = Depends(get_current_user),
):
    """删除{module}（软删除）"""
    success = await service.delete({module}_id, user_id=current_user.id)
    if not success:
        raise HTTPException(status_code=404, detail="{Module} not found")
    return None
