# File: app/services/{module}_service.py
# Generated by: {agent-name}
# Date: {timestamp}
# Template: .trae/templates/python/service.template.py

from typing import List, Optional, Tuple, Dict, Any
from datetime import datetime
from app.core.database import get_db
from app.core.cache import CacheManager
import json
import logging

logger = logging.getLogger(__name__)


class {Model}Service:
    """{module}服务层"""

    CACHE_TTL = 300  # 缓存过期时间（秒）
    CACHE_PREFIX = "{module}:"

    def __init__(self):
        self.cache = CacheManager()
        self._db = None

    async def _get_db(self):
        """获取数据库连接"""
        if self._db is None:
            self._db = await get_db()
        return self._db

    def _cache_key(self, key: str) -> str:
        """生成缓存键"""
        return f"{self.CACHE_PREFIX}{key}"

    async def list(
        self,
        skip: int = 0,
        limit: int = 20,
        search: Optional[str] = None,
        status: Optional[str] = None,
        user_id: Optional[str] = None,
    ) -> Tuple[List[Dict[str, Any]], int]:
        """
        获取{module}列表

        Args:
            skip: 跳过数量
            limit: 返回数量
            search: 搜索关键词
            status: 状态筛选
            user_id: 用户ID

        Returns:
            (items, total) 元组
        """
        db = await self._get_db()

        try:
            # 构建查询条件
            conditions = ["tenant_id = $1"]
            params = [user_id]
            param_index = 2

            if search:
                conditions.append(f"name ILIKE ${param_index}")
                params.append(f"%{search}%")
                param_index += 1

            if status:
                conditions.append(f"status = ${param_index}")
                params.append(status)
                param_index += 1

            where_clause = " AND ".join(conditions)

            # 查询总数
            count_query = f"SELECT COUNT(*) FROM {module}s WHERE {where_clause}"
            total = await db.fetch_val(count_query, *params)

            # 查询列表
            query = f"""
                SELECT id, name, description, status, config,
                       created_at, updated_at
                FROM {module}s
                WHERE {where_clause}
                ORDER BY created_at DESC
                LIMIT ${param_index} OFFSET ${param_index + 1}
            """
            params.extend([limit, skip])

            rows = await db.fetch_all(query, *params)

            items = []
            for row in rows:
                items.append({
                    'id': str(row['id']),
                    'name': row['name'],
                    'description': row.get('description'),
                    'status': row['status'],
                    'config': row.get('config', {}),
                    'created_at': row['created_at'],
                    'updated_at': row['updated_at'],
                })

            return items, total

        except Exception as e:
            logger.error(f"Failed to list {module}s: {e}", exc_info=True)
            raise
        finally:
            await db.close()

    async def get(self, {module}_id: str, user_id: Optional[str] = None) -> Optional[Dict[str, Any]]:
        """
        获取单个{module}

        Args:
            {module}_id: {module} ID
            user_id: 用户ID

        Returns:
            {module}对象或None
        """
        cache_key = self._cache_key({module}_id)
        cached = await self.cache.get(cache_key)
        if cached:
            return json.loads(cached)

        db = await self._get_db()

        try:
            query = """
                SELECT id, name, description, status, config,
                       created_at, updated_at
                FROM {module}s
                WHERE id = $1 AND tenant_id = $2
            """
            row = await db.fetch_one(query, {module}_id, user_id)

            if not row:
                return None

            item = {
                'id': str(row['id']),
                'name': row['name'],
                'description': row.get('description'),
                'status': row['status'],
                'config': row.get('config', {}),
                'created_at': row['created_at'],
                'updated_at': row['updated_at'],
            }

            # 缓存结果
            await self.cache.setex(cache_key, self.CACHE_TTL, json.dumps(item))

            return item

        except Exception as e:
            logger.error(f"Failed to get {module} {module}_id: {e}", exc_info=True)
            raise
        finally:
            await db.close()

    async def create(
        self,
        name: str,
        user_id: str,
        description: Optional[str] = None,
        config: Optional[dict] = None,
    ) -> Dict[str, Any]:
        """
        创建{module}

        Args:
            name: 名称
            user_id: 用户ID
            description: 描述
            config: 配置

        Returns:
            创建的{module}对象
        """
        db = await self._get_db()

        try:
            query = """
                INSERT INTO {module}s (name, description, config, tenant_id, status, created_at, updated_at)
                VALUES ($1, $2, $3, $4, 'active', NOW(), NOW())
                RETURNING id, name, description, status, config, created_at, updated_at
            """
            row = await db.fetch_one(
                query, name, description, json.dumps(config or {}), user_id
            )

            return {
                'id': str(row['id']),
                'name': row['name'],
                'description': row.get('description'),
                'status': row['status'],
                'config': row.get('config', {}),
                'created_at': row['created_at'],
                'updated_at': row['updated_at'],
            }

        except Exception as e:
            logger.error(f"Failed to create {module}: {e}", exc_info=True)
            raise
        finally:
            await db.close()

    async def update(
        self,
        id: str,
        user_id: str,
        name: Optional[str] = None,
        description: Optional[str] = None,
        status: Optional[str] = None,
        config: Optional[dict] = None,
    ) -> Optional[Dict[str, Any]]:
        """
        更新{module}

        Args:
            id: {module} ID
            user_id: 用户ID
            name: 名称
            description: 描述
            status: 状态
            config: 配置

        Returns:
            更新后的{module}对象
        """
        db = await self._get_db()

        try:
            updates = []
            params = []
            param_index = 1

            if name is not None:
                updates.append(f"name = ${param_index}")
                params.append(name)
                param_index += 1

            if description is not None:
                updates.append(f"description = ${param_index}")
                params.append(description)
                param_index += 1

            if status is not None:
                updates.append(f"status = ${param_index}")
                params.append(status)
                param_index += 1

            if config is not None:
                updates.append(f"config = ${param_index}")
                params.append(json.dumps(config))
                param_index += 1

            if not updates:
                return await self.get(id, user_id)

            updates.append("updated_at = NOW()")
            params.extend([id, user_id])

            query = f"""
                UPDATE {module}s
                SET {', '.join(updates)}
                WHERE id = ${param_index} AND tenant_id = ${param_index + 1}
                RETURNING id, name, description, status, config, created_at, updated_at
            """

            row = await db.fetch_one(query, *params)

            if not row:
                return None

            # 清除缓存
            await self.cache.delete(self._cache_key(id))

            return {
                'id': str(row['id']),
                'name': row['name'],
                'description': row.get('description'),
                'status': row['status'],
                'config': row.get('config', {}),
                'created_at': row['created_at'],
                'updated_at': row['updated_at'],
            }

        except Exception as e:
            logger.error(f"Failed to update {module} {id}: {e}", exc_info=True)
            raise
        finally:
            await db.close()

    async def delete(self, {module}_id: str, user_id: str) -> bool:
        """
        删除{module}（软删除）

        Args:
            {module}_id: {module} ID
            user_id: 用户ID

        Returns:
            是否删除成功
        """
        db = await self._get_db()

        try:
            query = """
                UPDATE {module}s
                SET deleted_at = NOW(), updated_at = NOW()
                WHERE id = $1 AND tenant_id = $2 AND deleted_at IS NULL
            """
            result = await db.execute(query, {module}_id, user_id)

            # 清除缓存
            await self.cache.delete(self._cache_key({module}_id))

            return result == "DELETE 1"

        except Exception as e:
            logger.error(f"Failed to delete {module} {module}_id: {e}", exc_info=True)
            raise
        finally:
            await db.close()
