// Package: handler
// File: {entity}_handler.go
// Generated by: {agent-name}
// Date: {timestamp}
// Template: .trae/templates/go/handler.template.go

package handler

import (
	"net/http"

	"github.com/gin-gonic/gin"
	"xunjianbao/backend/internal/service"
	"xunjianbao/backend/pkg/response"
)

type {Entity}Handler struct {
	svc *service.{Entity}Service
}

func New{Entity}Handler(svc *service.{Entity}Service) *{Entity}Handler {
	return &{Entity}Handler{svc: svc}
}

// List 获取{Entity}列表
// @Summary 获取{Entity}列表
// @Description 获取分页的{Entity}列表，支持搜索和过滤
// @Tags {Entity}
// @Accept json
// @Produce json
// @Param page query int false "页码" default(1) minimum(1)
// @Param page_size query int false "每页数量" default(20) minimum(1) maximum(100)
// @Param search query string false "搜索关键词"
// @Security BearerAuth
// @Success 200 {object} response.Response{data=model.{Entity}ListResponse}
// @Failure 400 {object} response.ErrorResponse
// @Failure 401 {object} response.ErrorResponse
// @Failure 500 {object} response.ErrorResponse
// @Router /api/v1/{entities} [get]
func (h *{Entity}Handler) List(c *gin.Context) {
	var req struct {
		Page     int    `form:"page" binding:"omitempty,min=1"`
		PageSize int    `form:"page_size" binding:"omitempty,min=1,max=100"`
		Search   string `form:"search" binding:"omitempty,max=255"`
	}

	if err := c.ShouldBindQuery(&req); err != nil {
		response.BadRequest(c, err.Error())
		return
	}

	if req.Page == 0 {
		req.Page = 1
	}
	if req.PageSize == 0 {
		req.PageSize = 20
	}

	ctx := c.Request.Context()
	result, err := h.svc.List(ctx, req.Page, req.PageSize, req.Search)
	if err != nil {
		response.InternalError(c, err.Error())
		return
	}

	response.Success(c, result)
}

// Get 获取单个{Entity}
// @Summary 获取单个{Entity}
// @Description 根据ID获取{Entity}详情
// @Tags {Entity}
// @Accept json
// @Produce json
// @Param id path int true "{Entity} ID"
// @Security BearerAuth
// @Success 200 {object} response.Response{data=model.{Entity}}
// @Failure 400 {object} response.ErrorResponse
// @Failure 404 {object} response.ErrorResponse
// @Router /api/v1/{entities}/{id} [get]
func (h *{Entity}Handler) Get(c *gin.Context) {
	id := c.Param("id")
	if id == "" {
		response.BadRequest(c, "id is required")
		return
	}

	ctx := c.Request.Context()
	result, err := h.svc.Get(ctx, id)
	if err != nil {
		response.InternalError(c, err.Error())
		return
	}
	if result == nil {
		response.NotFound(c, "{Entity} not found")
		return
	}

	response.Success(c, result)
}

// Create 创建{Entity}
// @Summary 创建{Entity}
// @Description 创建新的{Entity}
// @Tags {Entity}
// @Accept json
// @Produce json
// @Param body body model.Create{Entity}Request true "创建请求"
// @Security BearerAuth
// @Success 201 {object} response.Response{data=model.{Entity}}
// @Failure 400 {object} response.ErrorResponse
// @Failure 500 {object} response.ErrorResponse
// @Router /api/v1/{entities} [post]
func (h *{Entity}Handler) Create(c *gin.Context) {
	var req model.Create{Entity}Request
	if err := c.ShouldBindJSON(&req); err != nil {
		response.BadRequest(c, err.Error())
		return
	}

	ctx := c.Request.Context()
	result, err := h.svc.Create(ctx, &req)
	if err != nil {
		response.InternalError(c, err.Error())
		return
	}

	response.Created(c, result)
}

// Update 更新{Entity}
// @Summary 更新{Entity}
// @Description 更新已存在的{Entity}
// @Tags {Entity}
// @Accept json
// @Produce json
// @Param id path int true "{Entity} ID"
// @Param body body model.Update{Entity}Request true "更新请求"
// @Security BearerAuth
// @Success 200 {object} response.Response{data=model.{Entity}}
// @Failure 400 {object} response.ErrorResponse
// @Failure 404 {object} response.ErrorResponse
// @Failure 500 {object} response.ErrorResponse
// @Router /api/v1/{entities}/{id} [put]
func (h *{Entity}Handler) Update(c *gin.Context) {
	id := c.Param("id")
	if id == "" {
		response.BadRequest(c, "id is required")
		return
	}

	var req model.Update{Entity}Request
	if err := c.ShouldBindJSON(&req); err != nil {
		response.BadRequest(c, err.Error())
		return
	}

	ctx := c.Request.Context()
	result, err := h.svc.Update(ctx, id, &req)
	if err != nil {
		response.InternalError(c, err.Error())
		return
	}
	if result == nil {
		response.NotFound(c, "{Entity} not found")
		return
	}

	response.Success(c, result)
}

// Delete 删除{Entity}
// @Summary 删除{Entity}
// @Description 软删除{Entity}
// @Tags {Entity}
// @Accept json
// @Produce json
// @Param id path int true "{Entity} ID"
// @Security BearerAuth
// @Success 200 {object} response.Response
// @Failure 400 {object} response.ErrorResponse
// @Failure 404 {object} response.ErrorResponse
// @Failure 500 {object} response.ErrorResponse
// @Router /api/v1/{entities}/{id} [delete]
func (h *{Entity}Handler) Delete(c *gin.Context) {
	id := c.Param("id")
	if id == "" {
		response.BadRequest(c, "id is required")
		return
	}

	ctx := c.Request.Context()
	err := h.svc.Delete(ctx, id)
	if err != nil {
		response.InternalError(c, err.Error())
		return
	}

	response.Success(c, gin.H{"message": "{Entity} deleted successfully"})
}
