// Package: model
// File: {entity}.go
// Generated by: {agent-name}
// Date: {timestamp}
// Template: .trae/templates/go/model.template.go

package model

import (
	"time"
)

type {Entity} struct {
	ID        uint64     `gorm:"primarykey" json:"id"`
	CreatedAt time.Time  `json:"created_at"`
	UpdatedAt time.Time  `json:"updated_at"`
	DeletedAt *time.Time `gorm:"index" json:"-"`

	Name     string `gorm:"size:255;not null" json:"name"`
	Status   string `gorm:"size:32;default:active;index" json:"status"`
	TenantID string `gorm:"size:64;not null;index" json:"tenant_id"`
}

func ({Entity}) TableName() string {
	return "{entities}"
}

type Create{Entity}Request struct {
	Name string `json:"name" binding:"required,min=1,max=255"`
}

type Update{Entity}Request struct {
	Name   string `json:"name" binding:"omitempty,min=1,max=255"`
	Status string `json:"status" binding:"omitempty,oneof=active inactive"`
}

type {Entity}ListResponse struct {
	Items      []*{Entity} `json:"items"`
	Pagination Pagination  `json:"pagination"`
}

type Pagination struct {
	Page       int   `json:"page"`
	PageSize   int   `json:"page_size"`
	Total      int64 `json:"total"`
	TotalPages int   `json:"total_pages"`
}
