// Package: repository
// File: {entity}_repository.go
// Generated by: {agent-name}
// Date: {timestamp}
// Template: .trae/templates/go/repository.template.go

package repository

import (
	"context"

	"xunjianbao/backend/internal/model"
	"gorm.io/gorm"
)

type {Entity}Repository struct {
	db *gorm.DB
}

func New{Entity}Repository(db *gorm.DB) *{Entity}Repository {
	return &{Entity}Repository{db: db}
}

func (r *{Entity}Repository) List(ctx context.Context, limit, offset int, search string) ([]model.{Entity}, int64, error) {
	var entities []model.{Entity}
	var total int64

	query := r.db.WithContext(ctx).Model(&model.{Entity}{})

	if search != "" {
		query = query.Where("name ILIKE ?", "%"+search+"%")
	}

	if err := query.Count(&total).Error; err != nil {
		return nil, 0, err
	}

	if err := query.
		Order("created_at DESC").
		Limit(limit).
		Offset(offset).
		Find(&entities).Error; err != nil {
		return nil, 0, err
	}

	return entities, total, nil
}

func (r *{Entity}Repository) Get(ctx context.Context, id string) (*model.{Entity}, error) {
	var entity model.{Entity}
	err := r.db.WithContext(ctx).First(&entity, id).Error
	if err != nil {
		if err == gorm.ErrRecordNotFound {
			return nil, nil
		}
		return nil, err
	}
	return &entity, nil
}

func (r *{Entity}Repository) Create(ctx context.Context, entity *model.{Entity}) error {
	return r.db.WithContext(ctx).Create(entity).Error
}

func (r *{Entity}Repository) Update(ctx context.Context, entity *model.{Entity}) error {
	return r.db.WithContext(ctx).Save(entity).Error
}

func (r *{Entity}Repository) Delete(ctx context.Context, id string) error {
	return r.db.WithContext(ctx).Delete(&model.{Entity}{}, id).Error
}
