// Package: service
// File: {entity}_service.go
// Generated by: {agent-name}
// Date: {timestamp}
// Template: .trae/templates/go/service.template.go

package service

import (
	"context"

	"xunjianbao/backend/internal/model"
	"xunjianbao/backend/internal/repository"
)

type {Entity}Service struct {
	repo *repository.{Entity}Repository
}

func New{Entity}Service(repo *repository.{Entity}Repository) *{Entity}Service {
	return &{Entity}Service{repo: repo}
}

func (s *{Entity}Service) List(ctx context.Context, page, pageSize int, search string) (*model.{Entity}ListResponse, error) {
	offset := (page - 1) * pageSize

	entities, total, err := s.repo.List(ctx, pageSize, offset, search)
	if err != nil {
		return nil, err
	}

	totalPages := (total + pageSize - 1) / pageSize

	return &model.{Entity}ListResponse{
		Items: entities,
		Pagination: model.Pagination{
			Page:       page,
			PageSize:   pageSize,
			Total:      total,
			TotalPages: totalPages,
		},
	}, nil
}

func (s *{Entity}Service) Get(ctx context.Context, id string) (*model.{Entity}, error) {
	return s.repo.Get(ctx, id)
}

func (s *{Entity}Service) Create(ctx context.Context, req *model.Create{Entity}Request) (*model.{Entity}, error) {
	entity := &model.{Entity}{
		Name: req.Name,
	}

	if err := s.repo.Create(ctx, entity); err != nil {
		return nil, err
	}

	return entity, nil
}

func (s *{Entity}Service) Update(ctx context.Context, id string, req *model.Update{Entity}Request) (*model.{Entity}, error) {
	entity, err := s.repo.Get(ctx, id)
	if err != nil {
		return nil, err
	}
	if entity == nil {
		return nil, nil
	}

	if req.Name != "" {
		entity.Name = req.Name
	}
	if req.Status != "" {
		entity.Status = req.Status
	}

	if err := s.repo.Update(ctx, entity); err != nil {
		return nil, err
	}

	return entity, nil
}

func (s *{Entity}Service) Delete(ctx context.Context, id string) error {
	return s.repo.Delete(ctx, id)
}
